UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/usuario
    requirements:
        _locale: es|en

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: es|en

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: es|en

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: es|en

pagina_estatica:
    pattern:    /{_locale}/sitio/{pagina}/
    defaults:    {_controller: OfertaBundle:Sitio:estatica}
    requirements:
        _locale: es|en
    
portada:
    pattern: /{_locale}/{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, _locale: es }
    requirements:
        _locale: es|en

_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }
    
    
       
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
