UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    pattern:    /sitio/{pagina}/
    defaults:    {_controller: OfertaBundle:Sitio:estatica}
    
portada:
    pattern: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }

_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }
    
    
       
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
